<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>TTFLoaderMono</AssemblyName>
    <Description>BepInEx plugin to load TTF fonts directly</Description>
    <Version>1.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>TTFLoaderMono</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- if v6 -->
    <!-- <PackageReference Include="BepInEx.Unity.Mono" Version="6.0.0-be.*" IncludeAssets="compile" /> -->
    <!-- if v5 -->
    <PackageReference Include="BepInEx.BaseLib" Version="5.4.*" IncludeAssets="compile" />

    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <!-- if v5 -->
    <Reference Include="UnityEngine">
      <HintPath>libs\UnityEngine.dll</HintPath>
    </Reference>


    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>libs\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>libs\UnityEngine.TextRenderingModule.dll</HintPath>

      <!-- FIX: 类型“Font”同时存在于“UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral,
      PublicKeyToken=null”和“UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null”中 -->
      <Aliases>textrender</Aliases>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>libs\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>libs\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>